# Copyright 2021 The forwarder Authors. All rights reserved.
# Use of this source code is governed by a MIT
# license that can be found in the LICENSE file.

---
name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out code into the Go module directory"
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Setup golangci-lint
        uses: golangci/golangci-lint-action@v3.2.0
        with:
          version: v1.46.2
          args: "--timeout 5m -v -c .golangci.yml"

      - name: Lint
        run: golangci-lint run -v -c .golangci.yml

      - name: Test
        run: make test coverage

      - name: Test Integration
        run: make test-integration coverage
